"""Type stubs for awa._awa (PyO3 extension module)."""

from __future__ import annotations

from enum import IntEnum
from typing import Any, Awaitable, Callable, overload

class JobState(IntEnum):
    Scheduled = ...
    Available = ...
    Running = ...
    Completed = ...
    Retryable = ...
    Failed = ...
    Cancelled = ...

class Job:
    @property
    def id(self) -> int: ...
    @property
    def kind(self) -> str: ...
    @property
    def queue(self) -> str: ...
    @property
    def state(self) -> JobState: ...
    @property
    def priority(self) -> int: ...
    @property
    def attempt(self) -> int: ...
    @property
    def max_attempts(self) -> int: ...
    @property
    def tags(self) -> list[str]: ...
    @property
    def args(self) -> dict[str, Any]: ...
    @property
    def metadata(self) -> dict[str, Any]: ...
    @property
    def run_at(self) -> str: ...
    @property
    def deadline(self) -> str | None: ...
    @property
    def created_at(self) -> str: ...
    @property
    def finalized_at(self) -> str | None: ...

class RetryAfter:
    seconds: float
    def __init__(self, seconds: float) -> None: ...

class Snooze:
    seconds: float
    def __init__(self, seconds: float) -> None: ...

class Cancel:
    reason: str
    def __init__(self, reason: str = "cancelled by handler") -> None: ...

class Transaction:
    async def execute(self, query: str, args: list[Any]) -> int: ...
    async def fetch_one(self, query: str, args: list[Any]) -> dict[str, Any]: ...
    async def insert(
        self,
        args: Any,
        *,
        kind: str | None = None,
        queue: str = "default",
        priority: int = 2,
        max_attempts: int = 25,
        tags: list[str] | None = None,
    ) -> Job: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...
    async def __aenter__(self) -> Transaction: ...
    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: Any | None,
    ) -> bool: ...

class Client:
    def __init__(
        self, database_url: str, max_connections: int = 10
    ) -> None: ...
    async def insert(
        self,
        args: Any,
        *,
        kind: str | None = None,
        queue: str = "default",
        priority: int = 2,
        max_attempts: int = 25,
        tags: list[str] | None = None,
        metadata: dict[str, Any] | None = None,
    ) -> Job: ...
    async def migrate(self) -> None: ...
    async def transaction(self) -> Transaction: ...
    def worker(
        self,
        args_type: type,
        *,
        kind: str | None = None,
        queue: str = "default",
    ) -> Callable[[Callable[..., Awaitable[Any]]], Callable[..., Awaitable[Any]]]: ...
    async def retry(self, job_id: int) -> Job | None: ...
    async def cancel(self, job_id: int) -> Job | None: ...
    async def pause_queue(
        self, queue: str, paused_by: str | None = None
    ) -> None: ...
    async def resume_queue(self, queue: str) -> None: ...
    async def drain_queue(self, queue: str) -> int: ...
    async def queue_stats(self) -> list[dict[str, Any]]: ...

# Functions
def derive_kind(name: str) -> str: ...
async def migrate(database_url: str) -> None: ...
def migrations() -> list[tuple[int, str, str]]: ...

# Exceptions
class AwaError(Exception): ...
class UniqueConflict(AwaError): ...
class SchemaNotMigrated(AwaError): ...
class UnknownJobKind(AwaError): ...
class SerializationError(AwaError): ...
class TerminalError(AwaError): ...
class DatabaseError(AwaError): ...
