"""Type stubs for awa._awa (PyO3 extension module)."""

from __future__ import annotations

from enum import IntEnum
from typing import Any, Awaitable, Callable, Generic, TypeVar

T = TypeVar("T")

class JobState(IntEnum):
    Scheduled = ...
    Available = ...
    Running = ...
    Completed = ...
    Retryable = ...
    Failed = ...
    Cancelled = ...

class Job(Generic[T]):
    @property
    def id(self) -> int: ...
    @property
    def kind(self) -> str: ...
    @property
    def queue(self) -> str: ...
    @property
    def state(self) -> JobState: ...
    @property
    def priority(self) -> int: ...
    @property
    def attempt(self) -> int: ...
    @property
    def max_attempts(self) -> int: ...
    @property
    def tags(self) -> list[str]: ...
    @property
    def args(self) -> T: ...
    @property
    def metadata(self) -> dict[str, Any]: ...
    @property
    def run_at(self) -> str: ...
    @property
    def deadline(self) -> str | None: ...
    @property
    def created_at(self) -> str: ...
    @property
    def finalized_at(self) -> str | None: ...
    def is_cancelled(self) -> bool: ...

class QueueHealth:
    @property
    def in_flight(self) -> int: ...
    @property
    def max_workers(self) -> int: ...
    @property
    def available(self) -> int: ...

class HealthCheck:
    @property
    def healthy(self) -> bool: ...
    @property
    def postgres_connected(self) -> bool: ...
    @property
    def poll_loop_alive(self) -> bool: ...
    @property
    def heartbeat_alive(self) -> bool: ...
    @property
    def shutting_down(self) -> bool: ...
    @property
    def leader(self) -> bool: ...
    @property
    def queues(self) -> dict[str, QueueHealth]: ...

class RetryAfter:
    seconds: float
    def __init__(self, seconds: float) -> None: ...

class Snooze:
    seconds: float
    def __init__(self, seconds: float) -> None: ...

class Cancel:
    reason: str
    def __init__(self, reason: str = "cancelled by handler") -> None: ...

class Transaction:
    async def execute(self, query: str, *args: Any) -> int: ...
    async def fetch_one(self, query: str, *args: Any) -> dict[str, Any]: ...
    async def fetch_optional(self, query: str, *args: Any) -> dict[str, Any] | None: ...
    async def fetch_all(self, query: str, *args: Any) -> list[dict[str, Any]]: ...
    async def insert(
        self,
        args: Any,
        *,
        kind: str | None = None,
        queue: str = "default",
        priority: int = 2,
        max_attempts: int = 25,
        tags: list[str] | None = None,
        metadata: dict[str, Any] | None = None,
        run_at: Any | None = None,
    ) -> Job[dict[str, Any]]: ...
    async def insert_many(
        self,
        jobs: list[Any],
        *,
        kind: str | None = None,
        queue: str = "default",
        priority: int = 2,
        max_attempts: int = 25,
        tags: list[str] | None = None,
        metadata: dict[str, Any] | None = None,
        run_at: Any | None = None,
    ) -> list[Job[dict[str, Any]]]: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...
    async def __aenter__(self) -> Transaction: ...
    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: Any | None,
    ) -> bool: ...

class Client:
    def __init__(
        self, database_url: str, max_connections: int = 10
    ) -> None: ...
    async def insert(
        self,
        args: Any,
        *,
        kind: str | None = None,
        queue: str = "default",
        priority: int = 2,
        max_attempts: int = 25,
        tags: list[str] | None = None,
        metadata: dict[str, Any] | None = None,
        run_at: Any | None = None,
    ) -> Job[dict[str, Any]]: ...
    async def migrate(self) -> None: ...
    async def transaction(self) -> Transaction: ...
    def worker(
        self,
        args_type: type[T],
        *,
        kind: str | None = None,
        queue: str = "default",
    ) -> Callable[[Callable[[Job[T]], Awaitable[Any]]], Callable[[Job[T]], Awaitable[Any]]]: ...
    async def retry(self, job_id: int) -> Job[dict[str, Any]] | None: ...
    async def cancel(self, job_id: int) -> Job[dict[str, Any]] | None: ...
    async def retry_failed(
        self, *, kind: str | None = None, queue: str | None = None
    ) -> list[Job[dict[str, Any]]]: ...
    async def discard_failed(self, kind: str) -> int: ...
    async def pause_queue(
        self, queue: str, paused_by: str | None = None
    ) -> None: ...
    async def resume_queue(self, queue: str) -> None: ...
    async def drain_queue(self, queue: str) -> int: ...
    async def queue_stats(self) -> list[dict[str, Any]]: ...
    async def list_jobs(
        self,
        *,
        state: str | None = None,
        kind: str | None = None,
        queue: str | None = None,
        limit: int = 100,
    ) -> list[Job[dict[str, Any]]]: ...
    async def health_check(self) -> HealthCheck: ...
    def periodic(
        self,
        name: str,
        cron_expr: str,
        args_type: type[T],
        args: T,
        *,
        timezone: str = "UTC",
        queue: str = "default",
        priority: int = 2,
        max_attempts: int = 25,
        tags: list[str] | None = None,
        metadata: dict[str, Any] | None = None,
    ) -> None: ...
    def start(
        self,
        queues: list[tuple[str, int]] | None = None,
        *,
        poll_interval_ms: int = 200,
    ) -> None: ...
    async def shutdown(self, timeout_ms: int = 2000) -> None: ...

# Functions
def derive_kind(name: str) -> str: ...
async def migrate(database_url: str) -> None: ...
def migrations() -> list[tuple[int, str, str]]: ...

# Exceptions
class AwaError(Exception): ...
class UniqueConflict(AwaError): ...
class SchemaNotMigrated(AwaError): ...
class UnknownJobKind(AwaError): ...
class SerializationError(AwaError): ...
class ValidationError(AwaError): ...
class TerminalError(AwaError): ...
class DatabaseError(AwaError): ...
